declare function modals(): void;
export { modals } from './modals.ts';
export { sliders } from './sliders.ts';
export { forms } from './forms.ts';
export { mask } from './mask.ts';
export { checkTextInputs } from './checkTextInputs.ts';
export { showMoreElements } from './showMoreElements.ts';
export { calculator } from './calculator.ts';
export { filter } from './filter.ts';
export { imagesSize } from './imagesSize.ts';
export { accordion } from './accordion.ts';
export { burger } from './burger.ts';
export { scrolling } from './scrolling.ts';
